import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import DevPicture from '../../public/images/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/icons';
import HireMe from '@/components/HireMe';
import lightBulb from '../../public/svgs/lightBulb.svg';

export default function Home () {
  return (
    <>
      <Head>
        <title>ObedRav</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2 mr-10'>
              <Image src={DevPicture} alt='DevImage' className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text='Turning Dreams Into Reality With Code' className='text-6xl text-left' />
              <p className='my-4 text-base font-medium'>
                As a software engineer developer, I am dedicated to turning ideas into innovative solutions through code.
                Explore my latest projects, where I showcase my expertise in various technologies and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link
                  href='/resume.pdf'
                  target='_blank'
                  className='bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                >
                  Resume <LinkArrow className='w-6 ml-1' />
                </Link>
                <Link
                  href='mailto:rayovianamiltonobed@gmail.com'
                  rel='noreferrer'
                  target='_blank'
                  className='ml-4 text-lg font-medium text-dark underline'
                >
                  Contact Me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />

        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt='Light' className='w-full h-auto' />
        </div>
      </main>
    </>
  );
}
